services:
 eduapi:
  env_file: .env
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  container_name: edu_wep_api
  environment:
      - ConnectionStrings__DefaultConnectionDataBase=Host=db;Port=${DB_PORT};Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}
      - ConnectionStrings__DefaultConnectionRedis=redis:6379
  depends_on:
   - db
   - redis
   - minio

 db:
  env_file: .env
  image: postgres:latest
  ports:
   - "5480:5432"
  environment:
   POSTGRES_USER: ${POSTGRES_USER}
   POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   POSTGRES_DB: ${POSTGRES_DB}
   POSTGRES_PORT: ${DB_PORT}  
  container_name: db_postgresql_container
  volumes:
      - postgres_data:/var/lib/postgresql/data 

 redis:
  image: redis:latest
  container_name: my_redis
  ports:
   - "6379:6379"
  volumes:
      - redis_data:/data  

 minio:
    image: minio/minio
    ports:
      - "9000:9000" 
      - "9001:9001"  
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:  
  redis_data:    
  minio_data:
