services:
 eduapi:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - "8080:8080"
  container_name: edu_wep_api
  depends_on:
   - db
 db:
  image: postgres:latest
  ports:
   - "5432:5432"
  environment:
   POSTGRES_USER: postgres
   POSTGRES_PASSWORD: 123
  container_name: db_postgresql_container

